version: '3'
services:
  web:
    image: "node"
    build: .
    command: "npm install"
    command: "npm install pm2 -g"
    command: "pm2 start server.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"