version: '3'
services:
  node:
    image: "node-todo-app"
    build: .
    command: "pm2 start server.js"
    ports:
      - "5000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"